//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoredProcedureAdvanced.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DatabaseEntities : DbContext
    {
        public DatabaseEntities()
            : base("name=DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
    
        public virtual ObjectResult<User> sp_GetAllUser()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<User>("sp_GetAllUser");
        }
    
        public virtual ObjectResult<User> sp_GetAllUser(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<User>("sp_GetAllUser", mergeOption);
        }
    
        public virtual ObjectResult<User> sp_GetUserCount(string searchValue)
        {
            var searchValueParameter = searchValue != null ?
                new ObjectParameter("searchValue", searchValue) :
                new ObjectParameter("searchValue", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<User>("sp_GetUserCount", searchValueParameter);
        }
    
        public virtual ObjectResult<User> sp_GetUserCount(string searchValue, MergeOption mergeOption)
        {
            var searchValueParameter = searchValue != null ?
                new ObjectParameter("searchValue", searchValue) :
                new ObjectParameter("searchValue", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<User>("sp_GetUserCount", mergeOption, searchValueParameter);
        }
    
        public virtual ObjectResult<User> sp_GetUserList(string searchValue, Nullable<int> start, Nullable<int> length)
        {
            var searchValueParameter = searchValue != null ?
                new ObjectParameter("searchValue", searchValue) :
                new ObjectParameter("searchValue", typeof(string));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(int));
    
            var lengthParameter = length.HasValue ?
                new ObjectParameter("length", length) :
                new ObjectParameter("length", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<User>("sp_GetUserList", searchValueParameter, startParameter, lengthParameter);
        }
    
        public virtual ObjectResult<User> sp_GetUserList(string searchValue, Nullable<int> start, Nullable<int> length, MergeOption mergeOption)
        {
            var searchValueParameter = searchValue != null ?
                new ObjectParameter("searchValue", searchValue) :
                new ObjectParameter("searchValue", typeof(string));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(int));
    
            var lengthParameter = length.HasValue ?
                new ObjectParameter("length", length) :
                new ObjectParameter("length", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<User>("sp_GetUserList", mergeOption, searchValueParameter, startParameter, lengthParameter);
        }
    }
}
