//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScormReading.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCourse
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string CourseTitle { get; set; }
        public string CourseLink { get; set; }
        public string CourseId { get; set; }
        public Nullable<int> percentageCompleted { get; set; }
        public string currentLesson { get; set; }
        public string lessonHeading { get; set; }
        public string lessonNumber { get; set; }
        public Nullable<int> IsCompleted { get; set; }
        public Nullable<int> IsPassed { get; set; }
        public Nullable<int> Result { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual User User { get; set; }
    }
}
